INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (1, 6, 10);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (1, 7, 14);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (1, 8, 15);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (1, 9, 9);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (1, 10, 8);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (1, 11, 27);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (1, 12, 11);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (2, 6, 14);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (2, 7, 27);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 2, 8, 13);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 2, 9, 18);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 2, 10, 22);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 2, 11, 13);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 2, 12, 18);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 3, 6, 14);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 3, 7, 26);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 3, 8, 27);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 3, 9, 23);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 3, 10, 8);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 3, 11, 6);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 3, 12, 24);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 4, 6, 24);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 4, 7, 12);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 4, 8, 30);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 4, 9, 15);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 4, 10, 6);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 4, 11, 18);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 4, 12, 22);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 5, 6, 11);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 5, 7, 20);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 5, 8, 27);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 5, 9, 24);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 5, 10, 20);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 5, 11, 7);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 5, 12, 30);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 6, 6, 5);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 6, 7, 26);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 6, 8, 19);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 6, 9, 20);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 6, 10, 16);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 6, 11, 18);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 6, 12, 5);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 7, 6, 12);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 7, 7, 25);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 7, 8, 11);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 7, 9, 20);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 7, 10, 21);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 7, 11, 6);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 7, 12, 23);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 8, 6, 21);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 8, 7, 25);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 8, 8, 14);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 8, 9, 10);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 8, 10, 20);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 8, 11, 19);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 8, 12, 22);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 9, 6, 29);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 9, 7, 21);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 9, 8, 13);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 9, 9, 15);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 9, 10, 24);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 9, 11, 7);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 9, 12, 7);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 10, 6, 10);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 10, 7, 16);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 10, 8, 6);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 10, 9, 28);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 10, 10, 12);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 10, 11, 22);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 10, 12, 14);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 11, 6, 17);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 11, 7, 28);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 11, 8, 24);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 11, 9, 28);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 11, 10, 16);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 11, 11, 24);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 11, 12, 5);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 12, 6, 8);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 12, 7, 29);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 12, 8, 28);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 12, 9, 29);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 12, 10, 25);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 12, 11, 9);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 12, 12, 22);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 13, 6, 27);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 13, 7, 14);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 13, 8, 29);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 13, 9, 30);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 13, 10, 25);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 13, 11, 13);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 13, 12, 28);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 14, 6, 12);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 14, 7, 10);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 14, 8, 7);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 14, 9, 27);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 14, 10, 9);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 14, 11, 17);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 14, 12, 17);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES ( 15, 6, 17);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (15, 7, 29);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (15, 8, 24);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (15, 9, 8);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (15, 10, 17);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (15, 11, 26);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (15, 12, 10);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (16, 6, 15);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (16, 7, 13);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (16, 8, 30);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (16, 9, 9);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (16, 10, 6);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (16, 11, 26);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (16, 12, 26);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (17, 6, 14);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (17, 7, 28);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (17, 8, 7);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (17, 9, 23);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (17, 10, 26);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (17, 11, 26);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (17, 12, 13);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (18, 6, 7);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (18, 7, 30);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (18, 8, 9);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (18, 9, 12);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (18, 10, 6);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (18, 11, 6);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (18, 12, 26);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (19, 6, 14);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (19, 7, 30);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (19, 8, 8);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (19, 9, 23);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (19, 10, 30);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (19, 11, 16);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (19, 12, 7);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (20, 6, 25);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (20, 7, 26);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (20, 8, 18);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (20, 9, 12);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (20, 10, 25);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (20, 11, 20);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (20, 12, 25);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (21, 5, 13);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (21, 6, 22);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (21, 7, 11);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (21, 8, 25);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (21, 9, 10);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (21, 10, 24);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (22, 5, 22);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (22, 6, 8);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (22, 7, 25);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (22, 8, 14);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (22, 9, 6);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (22, 10, 16);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (23, 5, 18);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (23, 6, 16);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (23, 7, 5);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (23, 8, 18);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (23, 9, 7);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (23, 10, 28);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (24, 5, 23);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (24, 6, 9);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (24, 7, 22);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (24, 8, 22);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (24, 9, 30);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (24, 10, 17);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (25, 5, 14);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (25, 6, 29);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (25, 7, 28);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (25, 8, 19);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (25, 9, 19);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (25, 10, 23);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (26, 5, 7);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (26, 6, 6);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (26, 7, 5);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (26, 8, 6);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (26, 9, 24);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (26, 10, 15);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (27, 5, 26);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (27, 6, 17);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (27, 7, 6);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (27, 8, 13);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (27, 9, 14);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (27, 10, 30);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (28, 5, 8);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (28, 6, 14);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (28, 7, 29);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (28, 8, 9);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (28, 9, 17);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (28, 10, 25);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (29, 5, 24);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (29, 6, 5);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (29, 7, 25);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (29, 8, 15);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (29, 9, 20);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (29, 10, 18);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (30, 5, 21);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (30, 6, 27);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (30, 7, 6);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (30, 8, 13);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (30, 9, 20);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (30, 10, 7);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (31, 5, 28);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (31, 6, 8);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (31, 7, 8);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (31, 8, 27);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (31, 9, 28);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (31, 10, 24);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (32, 5, 28);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (32, 6, 12);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (32, 7, 10);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (32, 8, 20);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (32, 9, 23);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (32, 10, 14);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (33, 5, 16);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (33, 6, 14);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (33, 7, 13);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (33, 8, 21);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (33, 9, 9);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (33, 10, 17);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (34, 5, 10);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (34, 6, 25);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (34, 7, 21);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (34, 8, 21);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (34, 9, 8);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (34, 10, 21);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (35, 5, 29);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (35, 6, 17);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (35, 7, 10);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (35, 8, 20);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (35, 9, 13);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (35, 10, 19);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (36, 5, 10);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (36, 6, 26);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (36, 7, 29);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (36, 8, 14);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (36, 9, 10);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (36, 10, 13);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (37, 5, 12);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (37, 6, 16);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (37, 7, 17);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (37, 8, 21);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (37, 9, 11);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (37, 10, 20);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (38, 5, 21);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (38, 6, 29);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (38, 7, 19);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (38, 8, 20);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (38, 9, 28);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (38, 10, 29);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (39, 5, 23);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (39, 6, 6);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (39, 7, 13);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (39, 8, 15);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (39, 9, 8);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (39, 10, 25);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (40, 5, 16);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (40, 6, 22);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (40, 7, 14);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (40, 8, 11);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (40, 9, 9);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (40, 10, 17);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (41, 3, 7);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (41, 4, 22);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (41, 5, 12);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (41, 6, 13);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (42, 3, 16);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (42, 4, 9);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (42, 5, 21);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (42, 6, 27);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (43, 3, 7);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (43, 4, 11);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (43, 5, 27);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (43, 6, 20);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (44, 3, 11);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (44, 4, 14);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (44, 5, 28);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (44, 6, 16);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (45, 3, 21);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (45, 4, 20);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (45, 5, 21);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (45, 6, 21);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (46, 3, 18);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (46, 4, 21);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (46, 5, 13);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (46, 6, 8);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (47, 3, 9);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (47, 4, 29);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (47, 5, 12);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (47, 6, 23);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (48, 3, 11);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (48, 4, 25);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (48, 5, 5);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (48, 6, 28);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (49, 3, 7);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (49, 4, 18);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (49, 5, 19);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (49, 6, 17);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (50, 3, 23);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (50, 4, 23);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (50, 5, 27);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (50, 6, 29);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (51, 3, 28);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (51, 4, 7);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (51, 5, 17);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (51, 6, 22);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (52, 3, 17);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (52, 4, 23);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (52, 5, 26);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (52, 6, 16);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (53, 3, 13);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (53, 4, 27);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (53, 5, 10);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (53, 6, 30);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (54, 3, 8);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (54, 4, 7);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (54, 5, 30);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (54, 6, 5);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (55, 3, 19);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (55, 4, 26);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (55, 5, 10);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (55, 6, 5);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (56, 3, 6);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (56, 4, 30);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (56, 5, 9);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (56, 6, 28);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (57, 3, 6);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (57, 4, 10);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (57, 5, 6);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (57, 6, 18);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (58, 3, 10);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (58, 4, 30);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (58, 5, 5);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (58, 6, 9);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (59, 3, 30);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (59, 4, 27);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (59, 5, 14);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (59, 6, 9);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (60, 3, 13);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (60, 4, 16);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (60, 5, 30);
INSERT INTO PRODUCT_SIZES (shoeId, size, quantity) VALUES (60, 6, 30);