<?php

$SHOE_LIST_MEN = [
	[
		"shoeId" => 1,
		"brand" => "NIKE",
		"gender" => "MEN",
		"category" => "Sneakers",
		"description" => "Lightweight breathable sneakers for daily wear",
		"price" => 1799.0,
		"discount" => 15,
		"rating" => 4.2,
		"url" => "../assets/men_shoes/shoe_6.jpeg",
	],
	[
		"shoeId" => 2,
		"brand" => "PUMA",
		"gender" => "MEN",
		"category" => "Sneakers",
		"description" => "Classic low-top sneakers with modern twist",
		"price" => 1899.0,
		"discount" => 10,
		"rating" => 4.3,
		"url" => "../assets/men_shoes/shoe_7.webp",
	],
	[
		"shoeId" => 3,
		"brand" => "WOODLAND",
		"gender" => "MEN",
		"category" => "Boots",
		"description" => "Tough leather boots for outdoor adventures",
		"price" => 2599.0,
		"discount" => 20,
		"rating" => 4.5,
		"url" => "../assets/men_shoes/shoe_8.jpeg",
	],
	[
		"shoeId" => 4,
		"brand" => "RED TAPE",
		"gender" => "MEN",
		"category" => "Boots",
		"description" => "Stylish ankle boots for all-day comfort",
		"price" => 2299.0,
		"discount" => 12,
		"rating" => 4.1,
		"url" => "../assets/men_shoes/shoe_9.jpeg",
	],
	[
		"shoeId" => 5,
		"brand" => "BATA",
		"gender" => "MEN",
		"category" => "Sandals",
		"description" => "Comfortable sandals with soft footbed",
		"price" => 999.0,
		"discount" => 8,
		"rating" => 4.0,
		"url" => "../assets/men_shoes/shoe_10.jpeg",
	],
	[
		"shoeId" => 6,
		"brand" => "SPARX",
		"gender" => "MEN",
		"category" => "Sandals",
		"description" => "Durable sandals ideal for casual outings",
		"price" => 899.0,
		"discount" => 5,
		"rating" => 4.2,
		"url" => "../assets/men_shoes/shoe_11.avif",
	],
	[
		"shoeId" => 7,
		"brand" => "LOUIS PHILIPPE",
		"gender" => "MEN",
		"category" => "Loafers",
		"description" => "Elegant leather loafers for formal wear",
		"price" => 2699.0,
		"discount" => 18,
		"rating" => 4.6,
		"url" => "../assets/men_shoes/shoe_12.jpeg",
	],
	[
		"shoeId" => 8,
		"brand" => "HUSH PUPPIES",
		"gender" => "MEN",
		"category" => "Loafers",
		"description" => "Comfortable slip-on loafers with cushioned sole",
		"price" => 2399.0,
		"discount" => 15,
		"rating" => 4.4,
		"url" => "../assets/men_shoes/shoe_13.jpeg",
	],
	[
		"shoeId" => 9,
		"brand" => "NIKE",
		"gender" => "MEN",
		"category" => "Sneakers",
		"description" => "Performance sneakers with superior grip",
		"price" => 2099.0,
		"discount" => 10,
		"rating" => 4.5,
		"url" => "../assets/men_shoes/shoe_14.jpeg",
	],
	[
		"shoeId" => 10,
		"brand" => "PUMA",
		"gender" => "MEN",
		"category" => "Sneakers",
		"description" => "Trendy sneakers for casual wear",
		"price" => 1699.0,
		"discount" => 12,
		"rating" => 4.1,
		"url" => "../assets/men_shoes/shoe_15.jpeg",
	],
	[
		"shoeId" => 11,
		"brand" => "RED CHIEF",
		"gender" => "MEN",
		"category" => "Boots",
		"description" => "Rugged boots with padded collar",
		"price" => 2499.0,
		"discount" => 17,
		"rating" => 4.3,
		"url" => "../assets/men_shoes/shoe_16.jpeg",
	],
	[
		"shoeId" => 12,
		"brand" => "LEE COOPER",
		"gender" => "MEN",
		"category" => "Loafers",
		"description" => "Smart casual loafers for versatile use",
		"price" => 1999.0,
		"discount" => 14,
		"rating" => 4.2,
		"url" => "../assets/men_shoes/shoe_17.jpeg",
	],
];

$SHOE_LIST_WOMEN = [
	[
		"shoeId" => 101,
		"brand" => "NIKE",
		"gender" => "WOMEN",
		"category" => "Sneakers",
		"description" => "Stylish running sneakers with lightweight design",
		"price" => 2099.0,
		"discount" => 0,
		"rating" => 4.4,
		"url" => "../assets/women_shoes/shoe_1.jpg",
	],
	[
		"shoeId" => 102,
		"brand" => "PUMA",
		"gender" => "WOMEN",
		"category" => "Sneakers",
		"description" => "Breathable mesh sneakers perfect for workouts",
		"price" => 1899.0,
		"discount" => 10,
		"rating" => 4.3,
		"url" => "../assets/women_shoes/shoe_2.jpg",
	],
	[
		"shoeId" => 103,
		"brand" => "BATA",
		"gender" => "WOMEN",
		"category" => "Sandals",
		"description" => "Everyday wear sandals with adjustable straps",
		"price" => 799.0,
		"discount" => 8,
		"rating" => 4.0,
		"url" => "../assets/women_shoes/shoe_3.avif",
	],
	[
		"shoeId" => 104,
		"brand" => "CATWALK",
		"gender" => "WOMEN",
		"category" => "Heels",
		"description" => "Trendy block heels with cushioned footbed",
		"price" => 2299.0,
		"discount" => 15,
		"rating" => 4.2,
		"url" => "../assets/women_shoes/shoe_4.webp",
	],
	[
		"shoeId" => 105,
		"brand" => "METRO",
		"gender" => "WOMEN",
		"category" => "Heels",
		"description" => "Elegant high heels for evening wear",
		"price" => 2599.0,
		"discount" => 18,
		"rating" => 4.5,
		"url" => "../assets/women_shoes/shoe_5.jpg",
	],
	[
		"shoeId" => 106,
		"brand" => "HUSH PUPPIES",
		"gender" => "WOMEN",
		"category" => "Boots",
		"description" => "Warm ankle boots for winter comfort",
		"price" => 2799.0,
		"discount" => 20,
		"rating" => 4.6,
		"url" => "../assets/women_shoes/shoe_6.jpeg",
	],
	[
		"shoeId" => 107,
		"brand" => "NIKE",
		"gender" => "WOMEN",
		"category" => "Sneakers",
		"description" => "Modern sneakers with superior cushioning",
		"price" => 1999.0,
		"discount" => 10,
		"rating" => 4.3,
		"url" => "../assets/women_shoes/shoe_7.jpg",
	],
	[
		"shoeId" => 108,
		"brand" => "CATWALK",
		"gender" => "WOMEN",
		"category" => "Heels",
		"description" => "Glossy finish platform heels for parties",
		"price" => 2399.0,
		"discount" => 16,
		"rating" => 4.4,
		"url" => "../assets/women_shoes/shoe_8.jpg",
	],
	[
		"shoeId" => 109,
		"brand" => "PUMA",
		"gender" => "WOMEN",
		"category" => "Sneakers",
		"description" => "Sporty sneakers with breathable fabric",
		"price" => 1799.0,
		"discount" => 12,
		"rating" => 4.1,
		"url" => "../assets/women_shoes/shoe_9.jpg",
	],
	[
		"shoeId" => 110,
		"brand" => "BATA",
		"gender" => "WOMEN",
		"category" => "Sandals",
		"description" => "Lightweight slip-on sandals for casual use",
		"price" => 699.0,
		"discount" => 5,
		"rating" => 4.0,
		"url" => "../assets/women_shoes/shoe_10.webp",
	],
	[
		"shoeId" => 111,
		"brand" => "HUSH PUPPIES",
		"gender" => "WOMEN",
		"category" => "Boots",
		"description" => "Water-resistant boots with soft lining",
		"price" => 2899.0,
		"discount" => 18,
		"rating" => 4.5,
		"url" => "../assets/women_shoes/shoe_11.jpeg",
	],
	[
		"shoeId" => 112,
		"brand" => "METRO",
		"gender" => "WOMEN",
		"category" => "Heels",
		"description" => "Classy kitten heels for daily wear",
		"price" => 1999.0,
		"discount" => 10,
		"rating" => 4.2,
		"url" => "../assets/women_shoes/shoe_12.jpg",
	]
];

$SHOE_LIST_BOYS = [
	[
		"shoeId" => 201,
		"brand" => "NIKE",
		"gender" => "KIDS",
		"category" => "Sneakers",
		"description" => "Lightweight kids sneakers with breathable upper",
		"price" => 1499.0,
		"discount" => 10,
		"rating" => 4.3,
		"url" => "../assets/boys_shoes/shoe_1.jpg",
	],
	[
		"shoeId" => 202,
		"brand" => "PUMA",
		"gender" => "KIDS",
		"category" => "Sneakers",
		"description" => "Sporty sneakers with cushioned sole for all-day comfort",
		"price" => 1599.0,
		"discount" => 12,
		"rating" => 4.2,
		"url" => "../assets/boys_shoes/shoe_2.jpg",
	],
	[
		"shoeId" => 203,
		"brand" => "BATA",
		"gender" => "KIDS",
		"category" => "School Shoes",
		"description" => "Formal school shoes with strong grip and durability",
		"price" => 899.0,
		"discount" => 8,
		"rating" => 4.1,
		"url" => "../assets/boys_shoes/shoe_3.jpg",
	],
	[
		"shoeId" => 204,
		"brand" => "SPARX",
		"gender" => "KIDS",
		"category" => "Sandals",
		"description" => "Velcro strap sandals perfect for playtime",
		"price" => 799.0,
		"discount" => 5,
		"rating" => 4.0,
		"url" => "../assets/boys_shoes/shoe_4.jpg",
	],
	[
		"shoeId" => 205,
		"brand" => "ACTION",
		"gender" => "KIDS",
		"category" => "Sneakers",
		"description" => "Active wear sneakers with flexible outsole",
		"price" => 1399.0,
		"discount" => 10,
		"rating" => 4.2,
		"url" => "../assets/boys_shoes/shoe_5.jpg",
	],
	[
		"shoeId" => 206,
		"brand" => "ACTION",
		"gender" => "KIDS",
		"category" => "Boots",
		"description" => "Stylish ankle boots for kids' outings",
		"price" => 1799.0,
		"discount" => 15,
		"rating" => 4.4,
		"url" => "../assets/boys_shoes/shoe_6.jpeg",
	],
	[
		"shoeId" => 207,
		"brand" => "NIKE",
		"gender" => "KIDS",
		"category" => "Sneakers",
		"description" => "Trendy sneakers for everyday wear",
		"price" => 1699.0,
		"discount" => 12,
		"rating" => 4.3,
		"url" => "../assets/boys_shoes/shoe_7.jpg",
	],
	[
		"shoeId" => 208,
		"brand" => "SPARX",
		"gender" => "KIDS",
		"category" => "Sandals",
		"description" => "Comfortable sandals for summer days",
		"price" => 699.0,
		"discount" => 7,
		"rating" => 4.0,
		"url" => "../assets/boys_shoes/shoe_8.jpg",
	],
	[
		"shoeId" => 209,
		"brand" => "PUMA",
		"gender" => "KIDS",
		"category" => "Boots",
		"description" => "Durable boots with padded interior",
		"price" => 1899.0,
		"discount" => 14,
		"rating" => 4.5,
		"url" => "../assets/boys_shoes/shoe_9.jpeg",
	],
	[
		"shoeId" => 210,
		"brand" => "ACTION",
		"gender" => "KIDS",
		"category" => "School Shoes",
		"description" => "Black school shoes with anti-slip sole",
		"price" => 999.0,
		"discount" => 6,
		"rating" => 4.1,
		"url" => "../assets/boys_shoes/shoe_10.jpg",
	],
	[
		"shoeId" => 211,
		"brand" => "BATA",
		"gender" => "KIDS",
		"category" => "Sandals",
		"description" => "Soft padded sandals with cartoon prints",
		"price" => 749.0,
		"discount" => 5,
		"rating" => 4.0,
		"url" => "../assets/boys_shoes/shoe_11.jpg",
	],
	[
		"shoeId" => 212,
		"brand" => "ACTION",
		"gender" => "KIDS",
		"category" => "Boots",
		"description" => "Cool boots with sturdy rubber outsole",
		"price" => 1999.0,
		"discount" => 18,
		"rating" => 4.3,
		"url" => "../assets/boys_shoes/shoe_12.jpeg",
	]
];



// Ensure GET
if ($_SERVER['REQUEST_METHOD'] === 'GET') {
	header('Content-Type: application/json');

	$uri = $_SERVER['REQUEST_URI'];
	$normalizedUri = str_replace('/api/app.php', '', $uri);
	$parts = explode('/', $normalizedUri);
	$collection = $parts[2] ?? null; // 'sneakers'

	//echo "Collection: " . $collection . "\n";

	if ($collection === "men") {
		http_response_code(200);
		echo json_encode(array_values($SHOE_LIST_MEN));
	} else if ($collection === "women") {
		http_response_code(200);
		echo json_encode(array_values($SHOE_LIST_WOMEN));
	} else if ($collection === "boys") {
		http_response_code(200);
		echo json_encode(array_values($SHOE_LIST_BOYS));
	} else {
		http_response_code(400);
		echo json_encode(['error' => 'Invalid collection']);
	}
} else {
	http_response_code(405);
	header('Content-Type: application/json');
	echo json_encode(['error' => 'Method Not Allowed']);
}
